apiVersion: apps/v1
kind: Deployment

metadata:
  name: loki
  namespace: observability

spec:
  replicas: 1

  selector:
    matchLabels:
      app: loki

  template:
    metadata:
      labels:
        app: loki

    spec:
      containers:
        - name: loki

          image: grafana/loki:latest

          args:
            - -config.file=/etc/loki/local-config.yaml

          ports:
            - containerPort: 3100

          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki

            - name: loki-storage
              mountPath: /loki

      volumes:
        - name: loki-config
          configMap:
            name: loki-config

        - name: loki-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service

metadata:
  name: loki
  namespace: observability

spec:
  selector:
    app: loki

  ports:
    - port: 3100
      targetPort: 3100
